@startuml Npc 118 - Curly (Boss)
[*] --> 0000

0000 : Init
0000 --> 0001

0001 : Wait for ANP

0010 : Start boss fight
note left of 0010
Set random wait between 50-100
Face player
Become shootable
end note
0010 -[dashed]-> 0011

0011 : Wait
0011 --> 0013 : Wait elapsed

0013 : Start walking
note left of 0013
Set random wait between 50-100
Face player
end note
0013 -[dashed]-> 0014

0014 : Walk
0014 --> 0020 : Wait elapsed
note on link : Play charge sound effect

0020 : Charge up
note left of 0020
Face player
Slow to a stop
end note
0020 --> 0021 : After 50 ticks

0021 : Open fire!
note left of 0021 : Every 4 ticks
0021 --> 0010 : After 30 ticks

0030 : Missile Bubble
note left of 0030
This state is queued whenever
a normal missile is on screen
while Curly is in states 11-29.
This transition also makes
Curly invulnerable/unshootable.
end note
0030 --> 0010 : After 30 ticks

@enduml