@startuml Npc 318 - Mesa (Dead)
[*] --> 0000

0000 : Start dying
note right of 0000
Turn off shootable, ignore solidity, and soft solid
Set momentum to 1px/s up, 1/8px/s back
Play sound 54
end note
0000 --> 0001

0001 : Waiting to land
0001 --> 0001: Airborne
0001 --> 0002: Grounded

0002 : Dying
0002 --> [*] : 50 ticks passed
note right of 0002 : Set condition bit 8 (die next tick)

@enduml